[0m12:06:35.056194 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110f49ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1107f79d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1107f63d0>]}


============================== 12:06:35.058615 | d98ef979-bb1a-4990-a8d8-e684446b8a86 ==============================
[0m12:06:35.058615 [info ] [MainThread]: Running with dbt=1.7.0
[0m12:06:35.058948 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/alexheston/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:06:35.059234 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/alexheston/.dbt')}
[0m12:06:35.059422 [info ] [MainThread]: Creating dbt configuration folder at 
[0m12:06:48.683854 [debug] [MainThread]: Starter project path: /opt/homebrew/lib/python3.11/site-packages/dbt/include/starter_project
[0m12:06:48.701565 [info ] [MainThread]: 
Your new dbt project "dec_debt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:06:48.702131 [info ] [MainThread]: Setting up your profile.
[0m12:07:16.403889 [error] [MainThread]: Encountered an error:
dlopen(/Users/alexheston/Library/Python/3.11/lib/python/site-packages/_cffi_backend.cpython-311-darwin.so, 0x0002): tried: '/Users/alexheston/Library/Python/3.11/lib/python/site-packages/_cffi_backend.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/alexheston/Library/Python/3.11/lib/python/site-packages/_cffi_backend.cpython-311-darwin.so' (no such file), '/Users/alexheston/Library/Python/3.11/lib/python/site-packages/_cffi_backend.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
[0m12:07:16.409989 [error] [MainThread]: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/cli/requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/cli/requires.py", line 75, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/cli/main.py", line 515, in init
    results = task.run()
              ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/task/init.py", line 344, in run
    self.setup_profile(profile_name)
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/task/init.py", line 264, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/task/init.py", line 174, in create_profile_from_target
    load_plugin(adapter)
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/adapters/factory.py", line 212, in load_plugin
    return FACTORY.load_plugin(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/adapters/factory.py", line 58, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/adapters/snowflake/__init__.py", line 2, in <module>
    from dbt.adapters.snowflake.connections import SnowflakeConnectionManager  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dbt/adapters/snowflake/connections.py", line 17, in <module>
    from cryptography.hazmat.primitives import serialization
  File "/opt/homebrew/lib/python3.11/site-packages/cryptography/hazmat/primitives/serialization/__init__.py", line 7, in <module>
    from cryptography.hazmat.primitives._serialization import (
  File "/opt/homebrew/lib/python3.11/site-packages/cryptography/hazmat/primitives/_serialization.py", line 10, in <module>
    from cryptography.hazmat.primitives.hashes import HashAlgorithm
  File "/opt/homebrew/lib/python3.11/site-packages/cryptography/hazmat/primitives/hashes.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import openssl as rust_openssl
ImportError: dlopen(/Users/alexheston/Library/Python/3.11/lib/python/site-packages/_cffi_backend.cpython-311-darwin.so, 0x0002): tried: '/Users/alexheston/Library/Python/3.11/lib/python/site-packages/_cffi_backend.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/alexheston/Library/Python/3.11/lib/python/site-packages/_cffi_backend.cpython-311-darwin.so' (no such file), '/Users/alexheston/Library/Python/3.11/lib/python/site-packages/_cffi_backend.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))

[0m12:07:16.416403 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 41.380207, "process_user_time": 0.8565, "process_kernel_time": 0.173725, "process_mem_max_rss": "119275520", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m12:07:16.416767 [debug] [MainThread]: Command `dbt init` failed at 12:07:16.416693 after 41.38 seconds
[0m12:07:16.416995 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110f539d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110f50950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110806e50>]}
[0m12:07:16.417259 [debug] [MainThread]: Flushing usage events
[0m12:15:06.530643 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10de83610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10dea7a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10dea7f90>]}


============================== 12:15:06.533392 | 71566ac9-f9c7-45f0-b11a-c1672116de83 ==============================
[0m12:15:06.533392 [info ] [MainThread]: Running with dbt=1.8.5
[0m12:15:06.533734 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/alexheston/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt init', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:15:25.815461 [debug] [MainThread]: Starter project path: /opt/anaconda3/envs/dbt-env/lib/python3.11/site-packages/dbt/include/starter_project
[0m12:15:25.833310 [info ] [MainThread]: 
Your new dbt project "DBTdec" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:15:25.833763 [info ] [MainThread]: Setting up your profile.
[0m12:17:54.750733 [info ] [MainThread]: Profile DBTdec written to /Users/alexheston/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:17:54.907267 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 168.42065, "process_user_time": 0.737826, "process_kernel_time": 0.189765, "process_mem_max_rss": "118161408", "process_in_blocks": "0", "process_out_blocks": "0"}
[0m12:17:54.908261 [debug] [MainThread]: Command `dbt init` succeeded at 12:17:54.908123 after 168.42 seconds
[0m12:17:54.908808 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10dea9f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10deaa010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1060897d0>]}
[0m12:17:54.909338 [debug] [MainThread]: Flushing usage events
[0m12:27:24.377573 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109800290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108bc9650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109867450>]}


============================== 12:27:24.380182 | cbce19fd-4789-409e-8822-d5a7200aee10 ==============================
[0m12:27:24.380182 [info ] [MainThread]: Running with dbt=1.8.5
[0m12:27:24.380484 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/alexheston/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m12:27:24.380780 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/alexheston/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:27:24.388843 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.041216165, "process_user_time": 0.5088, "process_kernel_time": 0.13328, "process_mem_max_rss": "99909632", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m12:27:24.389292 [debug] [MainThread]: Command `dbt run` failed at 12:27:24.389167 after 0.04 seconds
[0m12:27:24.389581 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107990110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109839310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109838410>]}
[0m12:27:24.389792 [debug] [MainThread]: Flushing usage events
